### ISSUE TITLE
Setup VPN between servers and clients

### ISSUE THREAD

**Issue by aahutsal** [FairPriceRx/puppeteer-robot#3]
We're getting `Too many authentication failures` error daily. 

I should restart VNC server every morning. This is happening because VNC is listening on publicly available port and some hacking bots finds it and tries to brute-force password (this is a common practice to find vulnerable services over internet and hack them).

To avoid that we should close that port from being publicly available and make VPN (virtual private network) between servers. That will in the future allow to connect @FairPriceRx  support client computers via that machine (with real US IP address) to route all traffic. As the result you can get rid of existing VPN, which is:
- costly
- one more node in a chain

Estimated time to setup OpenVPN between server - 3 hours. On client computers that should be done by yourself with my assistance.

**Comment by FairPriceRx** [comment]
price of your work?
price of VPN? once?monthly?
could the bot make restart itself everyday, for ex, at 12 am? without human help?

**Comment by aahutsal** [comment]
1. Estimated time to setup OpenVPN between server - 3 hours. 
2. On client computers that should be done by yourself with my assistance. - can't estimate, it depends
3. VPN cost nothing in that case (acutally price is included into AWS bills for that server (free for 12 months) and Internet traffic (cheap currently - AWS bill for past 7 days - $0.00).
4. Restart will not be needed if we secure our server, close all ports from being accessible for public and use only VPN to connect. 

Basically all of that makes sence ONLY of AWS IP will be accepted by PayPal with no problems. Since AWS is publicly available hosting platform I'm not sure how does PayPal (and others) works with their IPs.
