### ISSUE TITLE
Shipping address could be different from Billing address

### ISSUE THREAD

**Issue by aahutsal** [FairPriceRx/puppeteer-robot#4]
This is a rare but possible situation. Taras should make some necessary changes in `wordpress` project, I should uncheck `Same as billing` checkbox and fill `Shipping address` information also, add and modify existing tests.

Estimated time: 3 hours

**Comment by FairPriceRx** [comment]
it`s place to be of such situations
What is the price of issue?

**Comment by aahutsal** [comment]
Estimated time: 3 hours

You know the rate.

**Comment by aahutsal** [comment]
Closed in #60578eb
